### ISSUE TITLE
Application is crashing on click of "Add new profile" or "Start Embedded Profile"

### ISSUE THREAD

**Issue by pallaviMN** [alalamav/android-openvpn-lib#1]
To make issues more managable, I would appriciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

**Comment by miladcoder** [comment]
same error

**Comment by miladcoder** [comment]
any support ?

**Comment by alalamav** [comment]
Hi, I'm afraid this project is no longer maintained. A while back, I was experimenting on how to leverage the OpenVPN protocol through their Android app. You should reach out to updsteam for help, since they will know better.

Thanks and apologies.
